version : "3"
services :
    redis :
        image : redis:alpine
        restart : always
        networks :
            - backend
    postgres :
        image : postgres:alpine
        restart : always
        networks :
            - backend
    api :
        build : "./server"
        image : api
        restart : always
        depends_on :
            - redis
            - postgres
        networks:
            - backend
    client :
        build : "./client"
        image : client
        restart : always
        ports :
            - 80:80
        networks :
            - frontend
            - backend
networks :
    frontend :
    backend :